"""empty message

Revision ID: 3e8848dd63b8
Revises:
Create Date: 2025-09-09 18:52:15.287359

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision = '3e8848dd63b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mcp_category',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='mcp tag name'),
        sa.Column('is_recommend', sa.Boolean(), nullable=False, comment='是否推荐类目'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='mcp category',
    )
    op.create_index(op.f('ix_mcp_category_id'), 'mcp_category', ['id'], unique=True)
    op.create_table(
        'mcp_router',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('mcp_id', sa.Integer(), nullable=False),
        sa.Column('mcp_endpoint', sa.Text(), nullable=True, comment='sse url'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='mcp server',
    )
    op.create_index(op.f('ix_mcp_router_id'), 'mcp_router', ['id'], unique=True)
    op.create_table(
        'sys_login_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('user_uuid', sa.String(length=50), nullable=False, comment='用户UUID'),
        sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
        sa.Column('status', sa.Integer(), nullable=False, comment='登录状态(0失败 1成功)'),
        sa.Column('ip', sa.String(length=50), nullable=False, comment='登录IP地址'),
        sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
        sa.Column('region', sa.String(length=50), nullable=True, comment='地区'),
        sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
        sa.Column('user_agent', sa.String(length=255), nullable=False, comment='请求头'),
        sa.Column('os', sa.String(length=50), nullable=True, comment='操作系统'),
        sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
        sa.Column('device', sa.String(length=50), nullable=True, comment='设备'),
        sa.Column('msg', mysql.LONGTEXT().with_variant(mysql.TEXT(), 'postgresql'), nullable=False, comment='提示消息'),
        sa.Column('login_time', sa.DateTime(), nullable=False, comment='登录时间'),
        sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='登录日志表',
    )
    op.create_index(op.f('ix_sys_login_log_id'), 'sys_login_log', ['id'], unique=True)
    op.create_table(
        'sys_opera_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('trace_id', sa.String(length=32), nullable=False, comment='请求跟踪 ID'),
        sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
        sa.Column('method', sa.String(length=20), nullable=False, comment='请求类型'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='操作模块'),
        sa.Column('path', sa.String(length=500), nullable=False, comment='请求路径'),
        sa.Column('ip', sa.String(length=50), nullable=False, comment='IP地址'),
        sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
        sa.Column('region', sa.String(length=50), nullable=True, comment='地区'),
        sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
        sa.Column('user_agent', sa.String(length=255), nullable=False, comment='请求头'),
        sa.Column('os', sa.String(length=50), nullable=True, comment='操作系统'),
        sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
        sa.Column('device', sa.String(length=50), nullable=True, comment='设备'),
        sa.Column('args', mysql.JSON(), nullable=True, comment='请求参数'),
        sa.Column('status', sa.Integer(), nullable=False, comment='操作状态（0异常 1正常）'),
        sa.Column('code', sa.String(length=20), nullable=False, comment='操作状态码'),
        sa.Column('msg', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='提示消息'),
        sa.Column('cost_time', sa.Float(), nullable=False, comment='请求耗时（ms）'),
        sa.Column('opera_time', sa.DateTime(timezone=True), nullable=False, comment='操作时间'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='操作日志表',
    )
    op.create_index(op.f('ix_sys_opera_log_id'), 'sys_opera_log', ['id'], unique=True)
    op.create_table(
        'sys_user',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=50), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
        sa.Column('nickname', sa.String(length=20), nullable=False, comment='昵称'),
        sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
        sa.Column(
            'salt',
            sa.VARBINARY(length=255).with_variant(postgresql.BYTEA(length=255), 'postgresql'),
            nullable=True,
            comment='加密盐',
        ),
        sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
        sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
        sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
        sa.Column('status', sa.Integer(), nullable=False, comment='用户账号状态(0停用 1正常)'),
        sa.Column(
            'is_superuser',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='超级权限(0否 1是)',
        ),
        sa.Column(
            'is_staff',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='后台管理登陆(0否 1是)',
        ),
        sa.Column(
            'is_multi_login',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='是否重复登陆(0否 1是)',
        ),
        sa.Column('join_time', sa.DateTime(timezone=True), nullable=False, comment='注册时间'),
        sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True, comment='上次登录'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uuid'),
        comment='用户表',
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table(
        'mcp_server',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='mcp server title'),
        sa.Column('description', sa.Text(), nullable=True, comment='描述'),
        sa.Column('transport', sa.String(length=20), nullable=True, comment='mcp transport type'),
        sa.Column('server_type', sa.String(length=20), nullable=True, comment='mcp server type'),
        sa.Column('envs', sa.JSON(), nullable=True, comment='环境变量'),
        sa.Column('image', sa.String(length=255), nullable=True, comment='镜像地址'),
        sa.Column('build_cmd', sa.Text(), nullable=True, comment='构建命令'),
        sa.Column('run_cmd', sa.Text(), nullable=True, comment='运行命令'),
        sa.Column('git', sa.String(length=255), nullable=True, comment='项目地址'),
        sa.Column('overview', sa.Text(), nullable=True, comment='介绍'),
        sa.Column('summary', sa.Text(), nullable=True, comment='AI总结的结果'),
        sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
        sa.Column('mcp_endpoint', sa.Text(), nullable=True, comment='sse url'),
        sa.Column('capabilities', sa.JSON(), nullable=True, comment='能力'),
        sa.Column('tools', sa.JSON(), nullable=True, comment='工具列表'),
        sa.Column('prompts', sa.JSON(), nullable=True, comment='提示词列表'),
        sa.Column('resources', sa.JSON(), nullable=True, comment='资源列表'),
        sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
        sa.Column('category_id', sa.BigInteger(), nullable=True, comment='MCP 分类ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['category_id'], ['mcp_category.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'title', name='uix_user_title'),
    )
    op.create_index(op.f('ix_mcp_server_id'), 'mcp_server', ['id'], unique=True)
    op.create_table(
        'sys_user_social',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('sid', sa.String(length=255), nullable=False, comment='第三方用户 ID'),
        sa.Column('source', sa.String(length=20), nullable=False, comment='第三方用户来源'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='用户社交表（OAuth2）',
    )
    op.create_index(op.f('ix_sys_user_social_id'), 'sys_user_social', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_social_id'), table_name='sys_user_social')
    op.drop_table('sys_user_social')
    op.drop_index(op.f('ix_mcp_server_id'), table_name='mcp_server')
    op.drop_table('mcp_server')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_opera_log_id'), table_name='sys_opera_log')
    op.drop_table('sys_opera_log')
    op.drop_index(op.f('ix_sys_login_log_id'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_mcp_router_id'), table_name='mcp_router')
    op.drop_table('mcp_router')
    op.drop_index(op.f('ix_mcp_category_id'), table_name='mcp_category')
    op.drop_table('mcp_category')
    # ### end Alembic commands ###
