"""empty message

Revision ID: 5d1fde65b10c
Revises:
Create Date: 2025-10-17 18:27:10.336677

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision = '5d1fde65b10c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'mcp_category',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='类目名称'),
        sa.Column('is_recommend', sa.Boolean(), nullable=False, comment='是否推荐类目'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='mcp category',
    )
    op.create_index(op.f('ix_mcp_category_id'), 'mcp_category', ['id'], unique=True)
    op.create_table(
        'mcp_router',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('mcp_id', sa.Integer(), nullable=False),
        sa.Column('mcp_endpoint', sa.Text(), nullable=True, comment='sse url'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='mcp server',
    )
    op.create_index(op.f('ix_mcp_router_id'), 'mcp_router', ['id'], unique=True)
    op.create_table(
        'sys_login_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('user_uuid', sa.String(length=50), nullable=False, comment='用户UUID'),
        sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
        sa.Column('status', sa.Integer(), nullable=False, comment='登录状态(0失败 1成功)'),
        sa.Column('ip', sa.String(length=50), nullable=False, comment='登录IP地址'),
        sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
        sa.Column('region', sa.String(length=50), nullable=True, comment='地区'),
        sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
        sa.Column('user_agent', sa.String(length=255), nullable=False, comment='请求头'),
        sa.Column('os', sa.String(length=50), nullable=True, comment='操作系统'),
        sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
        sa.Column('device', sa.String(length=50), nullable=True, comment='设备'),
        sa.Column('msg', mysql.LONGTEXT().with_variant(mysql.TEXT(), 'postgresql'), nullable=False, comment='提示消息'),
        sa.Column('login_time', sa.DateTime(), nullable=False, comment='登录时间'),
        sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='登录日志表',
    )
    op.create_index(op.f('ix_sys_login_log_id'), 'sys_login_log', ['id'], unique=True)
    op.create_table(
        'sys_opera_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('trace_id', sa.String(length=32), nullable=False, comment='请求跟踪 ID'),
        sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
        sa.Column('method', sa.String(length=20), nullable=False, comment='请求类型'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='操作模块'),
        sa.Column('path', sa.String(length=500), nullable=False, comment='请求路径'),
        sa.Column('ip', sa.String(length=50), nullable=False, comment='IP地址'),
        sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
        sa.Column('region', sa.String(length=50), nullable=True, comment='地区'),
        sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
        sa.Column('user_agent', sa.String(length=255), nullable=False, comment='请求头'),
        sa.Column('os', sa.String(length=50), nullable=True, comment='操作系统'),
        sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
        sa.Column('device', sa.String(length=50), nullable=True, comment='设备'),
        sa.Column('args', mysql.JSON(), nullable=True, comment='请求参数'),
        sa.Column('status', sa.Integer(), nullable=False, comment='操作状态（0异常 1正常）'),
        sa.Column('code', sa.String(length=20), nullable=False, comment='操作状态码'),
        sa.Column('msg', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='提示消息'),
        sa.Column('cost_time', sa.Float(), nullable=False, comment='请求耗时（ms）'),
        sa.Column('opera_time', sa.DateTime(timezone=True), nullable=False, comment='操作时间'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='操作日志表',
    )
    op.create_index(op.f('ix_sys_opera_log_id'), 'sys_opera_log', ['id'], unique=True)
    op.create_table(
        'sys_role',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='角色名称'),
        sa.Column('status', sa.Integer(), nullable=False, comment='角色状态（0停用 1正常）'),
        sa.Column('remark', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='备注'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='角色表',
    )
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=True)
    op.create_table(
        'sys_user',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=50), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
        sa.Column('nickname', sa.String(length=20), nullable=False, comment='昵称'),
        sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
        sa.Column(
            'salt',
            sa.VARBINARY(length=255).with_variant(postgresql.BYTEA(length=255), 'postgresql'),
            nullable=True,
            comment='加密盐',
        ),
        sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
        sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
        sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
        sa.Column('status', sa.Integer(), nullable=False, comment='用户账号状态(0停用 1正常)'),
        sa.Column(
            'is_superuser',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='超级权限(0否 1是)',
        ),
        sa.Column(
            'is_staff',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='后台管理登陆(0否 1是)',
        ),
        sa.Column(
            'is_multi_login',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='是否重复登陆(0否 1是)',
        ),
        sa.Column('join_time', sa.DateTime(timezone=True), nullable=False, comment='注册时间'),
        sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True, comment='上次登录时间'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uuid'),
        comment='用户表',
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table(
        'task_result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task_id', sa.String(length=155), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('result', sa.PickleType(), nullable=True),
        sa.Column('date_done', sa.DateTime(), nullable=True),
        sa.Column('traceback', sa.Text(), nullable=True),
        sa.Column('name', sa.String(length=155), nullable=True),
        sa.Column('args', sa.LargeBinary(), nullable=True),
        sa.Column('kwargs', sa.LargeBinary(), nullable=True),
        sa.Column('worker', sa.String(length=155), nullable=True),
        sa.Column('retries', sa.Integer(), nullable=True),
        sa.Column('queue', sa.String(length=155), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id'),
        comment='任务结果表',
    )
    op.create_table(
        'task_scheduler',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=50), nullable=False, comment='任务名称'),
        sa.Column('task', sa.String(length=255), nullable=False, comment='要运行的 Celery 任务'),
        sa.Column('args', sa.JSON(), nullable=True, comment='任务可接收的位置参数'),
        sa.Column('kwargs', sa.JSON(), nullable=True, comment='任务可接收的关键字参数'),
        sa.Column('queue', sa.String(length=255), nullable=True, comment='CELERY_TASK_QUEUES 中定义的队列'),
        sa.Column('exchange', sa.String(length=255), nullable=True, comment='低级别 AMQP 路由的交换机'),
        sa.Column('routing_key', sa.String(length=255), nullable=True, comment='低级别 AMQP 路由的路由密钥'),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='任务开始触发的时间'),
        sa.Column('expire_time', sa.DateTime(timezone=True), nullable=True, comment='任务不再触发的截止时间'),
        sa.Column('expire_seconds', sa.Integer(), nullable=True, comment='任务不再触发的秒数时间差'),
        sa.Column('type', sa.Integer(), nullable=False, comment='调度类型（0间隔 1定时）'),
        sa.Column('interval_every', sa.Integer(), nullable=True, comment='任务再次运行前的间隔周期数'),
        sa.Column('interval_period', sa.String(length=255), nullable=True, comment='任务运行之间的周期类型'),
        sa.Column('crontab', sa.String(length=50), nullable=True, comment='任务运行的 Crontab 计划'),
        sa.Column(
            'one_off', sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'), nullable=False, comment='是否仅运行一次'
        ),
        sa.Column(
            'enabled', sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'), nullable=False, comment='是否启用任务'
        ),
        sa.Column('total_run_count', sa.Integer(), nullable=False, comment='任务触发的总次数'),
        sa.Column('last_run_time', sa.DateTime(timezone=True), nullable=True, comment='任务最后触发的时间'),
        sa.Column('remark', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='备注'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='任务调度表',
    )
    op.create_index(op.f('ix_task_scheduler_id'), 'task_scheduler', ['id'], unique=True)
    op.create_table(
        'task_set_result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('taskset_id', sa.String(length=155), nullable=True),
        sa.Column('result', sa.PickleType(), nullable=True),
        sa.Column('date_done', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('taskset_id'),
        comment='任务集结果表',
    )
    op.create_table(
        'mcp_server',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('server_title', sa.String(length=255), nullable=False, comment='mcp server title'),
        sa.Column('server_name', sa.String(length=255), nullable=False, comment='mcp server name'),
        sa.Column('transport', sa.String(length=20), nullable=True, comment='streamable-http、sse、stdio'),
        sa.Column('server_type', sa.String(length=20), nullable=True, comment='hosted、local'),
        sa.Column('compile_type', sa.String(length=20), nullable=True, comment='编译类型'),
        sa.Column('runtime_type', sa.String(length=20), nullable=False, comment='运行环境'),
        sa.Column('server_config', sa.JSON(), nullable=True, comment='server config'),
        sa.Column('envs', sa.JSON(), nullable=True, comment='环境变量'),
        sa.Column('git', sa.String(length=255), nullable=True, comment='项目地址'),
        sa.Column('readme', sa.Text(), nullable=True, comment='项目介绍'),
        sa.Column('avatar', sa.String(length=255), nullable=True, comment='项目头像'),
        sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
        sa.Column('server_metadata', sa.JSON(), nullable=True, comment='mcp server config'),
        sa.Column('tools', sa.JSON(), nullable=True, comment='工具列表'),
        sa.Column('prompts', sa.JSON(), nullable=True, comment='提示词列表'),
        sa.Column('resources', sa.JSON(), nullable=True, comment='资源列表'),
        sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
        sa.Column('category_id', sa.BigInteger(), nullable=True, comment='MCP 分类ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['category_id'], ['mcp_category.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'server_name', name='uix_user_server_name'),
    )
    op.create_index(op.f('ix_mcp_server_id'), 'mcp_server', ['id'], unique=True)
    op.create_table(
        'sys_user_role',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
        sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
        sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', 'user_id', 'role_id'),
    )
    op.create_index(op.f('ix_sys_user_role_id'), 'sys_user_role', ['id'], unique=True)
    op.create_table(
        'sys_user_social',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('sid', sa.String(length=255), nullable=False, comment='第三方用户 ID'),
        sa.Column('source', sa.String(length=20), nullable=False, comment='第三方用户来源'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='用户社交表（OAuth2）',
    )
    op.create_index(op.f('ix_sys_user_social_id'), 'sys_user_social', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_social_id'), table_name='sys_user_social')
    op.drop_table('sys_user_social')
    op.drop_index(op.f('ix_sys_user_role_id'), table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_mcp_server_id'), table_name='mcp_server')
    op.drop_table('mcp_server')
    op.drop_table('task_set_result')
    op.drop_index(op.f('ix_task_scheduler_id'), table_name='task_scheduler')
    op.drop_table('task_scheduler')
    op.drop_table('task_result')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_opera_log_id'), table_name='sys_opera_log')
    op.drop_table('sys_opera_log')
    op.drop_index(op.f('ix_sys_login_log_id'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_mcp_router_id'), table_name='mcp_router')
    op.drop_table('mcp_router')
    op.drop_index(op.f('ix_mcp_category_id'), table_name='mcp_category')
    op.drop_table('mcp_category')
    # ### end Alembic commands ###
