"""empty message

Revision ID: 4749e906f64e
Revises: c1fc85ca108f
Create Date: 2025-09-23 15:50:22.433304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4749e906f64e'
down_revision = 'c1fc85ca108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('deploy_method', sa.String(length=20), nullable=False, comment='部署方式'))
    op.add_column('mcp_server', sa.Column('server_meta', sa.JSON(), nullable=True, comment='mcp server config'))
    op.drop_column('mcp_server', 'capabilities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('capabilities', mysql.JSON(), nullable=True, comment='能力'))
    op.drop_column('mcp_server', 'server_meta')
    op.drop_column('mcp_server', 'deploy_method')
    # ### end Alembic commands ###
