"""empty message

Revision ID: 401cd3678a27
Revises: 3e8848dd63b8
Create Date: 2025-09-09 21:15:07.226390

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '401cd3678a27'
down_revision = '3e8848dd63b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'mcp_category',
        'name',
        existing_type=mysql.VARCHAR(length=20),
        comment='类目名称',
        existing_comment='mcp tag name',
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'mcp_category',
        'name',
        existing_type=mysql.VARCHAR(length=20),
        comment='mcp tag name',
        existing_comment='类目名称',
        existing_nullable=False,
    )
    # ### end Alembic commands ###
