"""empty message

Revision ID: cadb97f46b78
Revises: c85ea8356210
Create Date: 2025-09-26 10:58:08.896628

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cadb97f46b78'
down_revision = 'c85ea8356210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('server_metadata', sa.JSON(), nullable=True, comment='mcp server config'))
    op.drop_column('mcp_server', 'server_meta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('server_meta', mysql.JSON(), nullable=True, comment='mcp server config'))
    op.drop_column('mcp_server', 'server_metadata')
    # ### end Alembic commands ###
