"""empty message

Revision ID: 8d93aa23851a
Revises: 1c1ae5d03f1b
Create Date: 2026-02-09 15:48:44.632934

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8d93aa23851a'
down_revision = '1c1ae5d03f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_server', sa.Column('avatar', sa.String(length=255), nullable=False, comment='agent avatar'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_server', 'avatar')
    # ### end Alembic commands ###
