"""empty message

Revision ID: 06483a45b8b9
Revises:
Create Date: 2026-02-07 19:36:18.575969

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '06483a45b8b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('raw_config', sa.JSON(), nullable=True, comment='raw config'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server', 'raw_config')
    # ### end Alembic commands ###
