"""empty message

Revision ID: 65a8582e213c
Revises: 9507b23b12b5
Create Date: 2026-02-09 17:33:27.056142

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65a8582e213c'
down_revision = '9507b23b12b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_server', 'raw_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('raw_config', mysql.JSON(), nullable=True, comment='raw config'))
    # ### end Alembic commands ###
