"""empty message

Revision ID: 09ce9664aeab
Revises: 06483a45b8b9
Create Date: 2026-02-07 23:27:20.149300

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09ce9664aeab'
down_revision = '06483a45b8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_server', sa.Column('is_recommend', sa.Boolean(), nullable=False, comment='是否推荐'))
    op.alter_column(
        'mcp_server',
        'is_public',
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
        existing_comment='是否公开',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'mcp_server',
        'is_public',
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
        existing_comment='是否公开',
    )
    op.drop_column('mcp_server', 'is_recommend')
    # ### end Alembic commands ###
