"""empty message

Revision ID: 9507b23b12b5
Revises: 8d93aa23851a
Create Date: 2026-02-09 16:39:56.394934

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9507b23b12b5'
down_revision = '8d93aa23851a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_skill', sa.Column('name', sa.String(length=255), nullable=False, comment='skill name'))
    op.add_column('agent_skill', sa.Column('description', sa.Text(), nullable=False, comment='skill description'))
    op.add_column('agent_skill', sa.Column('path', sa.String(length=255), nullable=False, comment='skill path'))
    op.drop_column('agent_skill', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_skill', sa.Column('title', mysql.VARCHAR(length=255), nullable=False, comment='agent name'))
    op.drop_column('agent_skill', 'path')
    op.drop_column('agent_skill', 'description')
    op.drop_column('agent_skill', 'name')
    # ### end Alembic commands ###
