"""empty message

Revision ID: c504b9716fbc
Revises: 5d7eca81228e
Create Date: 2026-02-10 22:47:43.487259

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c504b9716fbc'
down_revision = '5d7eca81228e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'agent_skill', sa.Column('repository', sa.String(length=255), nullable=False, comment='agent repository')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_skill', 'repository')
    # ### end Alembic commands ###
