"""empty message

Revision ID: 5d7eca81228e
Revises: 65a8582e213c
Create Date: 2026-02-10 22:46:28.127259

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5d7eca81228e'
down_revision = '65a8582e213c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_skill', sa.Column('avatar', sa.String(length=255), nullable=False, comment='agent avatar'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_skill', 'avatar')
    # ### end Alembic commands ###
