"""empty message

Revision ID: e4c103e92f02
Revises:
Create Date: 2026-02-19 21:21:46.368852

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql, postgresql

# revision identifiers, used by Alembic.
revision = 'e4c103e92f02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'agent_category',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='类目名称'),
        sa.Column('is_recommend', sa.Boolean(), nullable=False, comment='是否推荐类目'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='agent category',
    )
    op.create_index(op.f('ix_agent_category_id'), 'agent_category', ['id'], unique=True)
    op.create_table(
        'agent_server',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=255), nullable=False, comment='agent name'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='agent name'),
        sa.Column('avatar', sa.String(length=255), nullable=False, comment='agent avatar'),
        sa.Column('description', sa.Text(), nullable=True, comment='agent描述'),
        sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
        sa.Column('prologue', sa.Text(), nullable=False, comment='开场白'),
        sa.Column('tools', sa.JSON(), nullable=True, comment='工具列表'),
        sa.Column('knowledge', sa.JSON(), nullable=True, comment='知识库列表'),
        sa.Column('databases', sa.JSON(), nullable=True, comment='数据库列表'),
        sa.Column('skills', sa.JSON(), nullable=True, comment='skills列表'),
        sa.Column('enable_search', sa.Boolean(), nullable=True, comment='是否开启联网搜索'),
        sa.Column('enable_multimodal', sa.Boolean(), nullable=True, comment='是否多模态'),
        sa.Column('enable_suggest', sa.Boolean(), nullable=True, comment='问题建议'),
        sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
        sa.Column('category_id', sa.BigInteger(), nullable=True, comment='agent 分类ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='agent server',
    )
    op.create_index(op.f('ix_agent_server_category_id'), 'agent_server', ['category_id'], unique=False)
    op.create_index(op.f('ix_agent_server_id'), 'agent_server', ['id'], unique=True)
    op.create_index(op.f('ix_agent_server_user_id'), 'agent_server', ['user_id'], unique=False)
    op.create_table(
        'agent_skill',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=255), nullable=False, comment='skill name'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='skill title'),
        sa.Column('avatar', sa.String(length=255), nullable=False, comment='agent avatar'),
        sa.Column('description', sa.Text(), nullable=False, comment='skill description'),
        sa.Column('repository', sa.String(length=255), nullable=False, comment='agent repository'),
        sa.Column('path', sa.String(length=255), nullable=False, comment='skill path'),
        sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
        sa.Column('category_id', sa.BigInteger(), nullable=True, comment='skill 分类ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='agent server',
    )
    op.create_index(op.f('ix_agent_skill_category_id'), 'agent_skill', ['category_id'], unique=False)
    op.create_index(op.f('ix_agent_skill_id'), 'agent_skill', ['id'], unique=True)
    op.create_index(op.f('ix_agent_skill_user_id'), 'agent_skill', ['user_id'], unique=False)
    op.create_table(
        'mcp_category',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='类目名称'),
        sa.Column('is_recommend', sa.Integer(), nullable=False, comment='是否推荐类目'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='mcp category',
    )
    op.create_index(op.f('ix_mcp_category_id'), 'mcp_category', ['id'], unique=True)
    op.create_table(
        'mcp_server',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('server_title', sa.String(length=255), nullable=False, comment='mcp server title'),
        sa.Column('server_name', sa.String(length=255), nullable=False, comment='mcp server name'),
        sa.Column('transport', sa.String(length=20), nullable=True, comment='streamable-http、sse、stdio'),
        sa.Column('server_type', sa.String(length=20), nullable=True, comment='hosted、local'),
        sa.Column('compile_type', sa.String(length=20), nullable=True, comment='编译类型'),
        sa.Column('runtime_type', sa.String(length=20), nullable=False, comment='运行环境'),
        sa.Column('server_config', sa.JSON(), nullable=True, comment='server config'),
        sa.Column('envs', sa.JSON(), nullable=True, comment='环境变量'),
        sa.Column('git', sa.String(length=255), nullable=True, comment='项目地址'),
        sa.Column('readme', sa.Text(), nullable=True, comment='项目介绍'),
        sa.Column('avatar', sa.String(length=255), nullable=True, comment='项目头像'),
        sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
        sa.Column('server_metadata', sa.JSON(), nullable=True, comment='mcp server config'),
        sa.Column('tools', sa.JSON(), nullable=True, comment='工具列表'),
        sa.Column('prompts', sa.JSON(), nullable=True, comment='提示词列表'),
        sa.Column('resources', sa.JSON(), nullable=True, comment='资源列表'),
        sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
        sa.Column('is_recommend', sa.Boolean(), nullable=False, comment='是否推荐'),
        sa.Column('category_id', sa.BigInteger(), nullable=True, comment='MCP 分类ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'server_name', name='uix_user_server_name'),
    )
    op.create_index(op.f('ix_mcp_server_category_id'), 'mcp_server', ['category_id'], unique=False)
    op.create_index(op.f('ix_mcp_server_id'), 'mcp_server', ['id'], unique=True)
    op.create_index(op.f('ix_mcp_server_user_id'), 'mcp_server', ['user_id'], unique=False)
    op.create_table(
        'skill_category',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='类目名称'),
        sa.Column('is_recommend', sa.Boolean(), nullable=False, comment='是否推荐类目'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='skill category',
    )
    op.create_index(op.f('ix_skill_category_id'), 'skill_category', ['id'], unique=True)
    op.create_table(
        'sys_data_rule',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=512), nullable=False, comment='名称'),
        sa.Column('model', sa.String(length=64), nullable=False, comment='模型名称'),
        sa.Column('column', sa.String(length=32), nullable=False, comment='模型字段名'),
        sa.Column('operator', sa.Integer(), nullable=False, comment='运算符（0：and、1：or）'),
        sa.Column(
            'expression',
            sa.Integer(),
            nullable=False,
            comment='表达式（0：==、1：!=、2：>、3：>=、4：<、5：<=、6：in、7：not_in）',
        ),
        sa.Column('value', sa.String(length=256), nullable=False, comment='规则值'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='数据规则表',
    )
    op.create_index(op.f('ix_sys_data_rule_id'), 'sys_data_rule', ['id'], unique=True)
    op.create_table(
        'sys_data_scope',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=64), nullable=False, comment='名称'),
        sa.Column('status', sa.Integer(), nullable=False, comment='状态（0停用 1正常）'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='数据范围表',
    )
    op.create_index(op.f('ix_sys_data_scope_id'), 'sys_data_scope', ['id'], unique=True)
    op.create_table(
        'sys_data_scope_rule',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
        sa.Column('data_scope_id', sa.BigInteger(), nullable=False, comment='数据范围 ID'),
        sa.Column('data_rule_id', sa.BigInteger(), nullable=False, comment='数据规则 ID'),
        sa.PrimaryKeyConstraint('id', 'data_scope_id', 'data_rule_id'),
    )
    op.create_index(op.f('ix_sys_data_scope_rule_id'), 'sys_data_scope_rule', ['id'], unique=True)
    op.create_table(
        'sys_login_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('user_uuid', sa.String(length=50), nullable=False, comment='用户UUID'),
        sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
        sa.Column('status', sa.Integer(), nullable=False, comment='登录状态(0失败 1成功)'),
        sa.Column('ip', sa.String(length=50), nullable=False, comment='登录IP地址'),
        sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
        sa.Column('region', sa.String(length=50), nullable=True, comment='地区'),
        sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
        sa.Column('user_agent', sa.String(length=255), nullable=False, comment='请求头'),
        sa.Column('os', sa.String(length=50), nullable=True, comment='操作系统'),
        sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
        sa.Column('device', sa.String(length=50), nullable=True, comment='设备'),
        sa.Column('msg', mysql.LONGTEXT().with_variant(mysql.TEXT(), 'postgresql'), nullable=False, comment='提示消息'),
        sa.Column('login_time', sa.DateTime(), nullable=False, comment='登录时间'),
        sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='登录日志表',
    )
    op.create_index(op.f('ix_sys_login_log_id'), 'sys_login_log', ['id'], unique=True)
    op.create_table(
        'sys_menu',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('title', sa.String(length=64), nullable=False, comment='菜单标题'),
        sa.Column('name', sa.String(length=64), nullable=False, comment='菜单名称'),
        sa.Column('path', sa.String(length=200), nullable=True, comment='路由地址'),
        sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
        sa.Column('icon', sa.String(length=128), nullable=True, comment='菜单图标'),
        sa.Column('type', sa.Integer(), nullable=False, comment='菜单类型（0目录 1菜单 2按钮 3内嵌 4外链）'),
        sa.Column('component', sa.String(length=256), nullable=True, comment='组件路径'),
        sa.Column('perms', sa.String(length=128), nullable=True, comment='权限标识'),
        sa.Column('status', sa.Integer(), nullable=False, comment='菜单状态（0停用 1正常）'),
        sa.Column('display', sa.Integer(), nullable=False, comment='是否显示（0否 1是）'),
        sa.Column('cache', sa.Integer(), nullable=False, comment='是否缓存（0否 1是）'),
        sa.Column('link', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='外链地址'),
        sa.Column('remark', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='备注'),
        sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父菜单ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='菜单表',
    )
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=True)
    op.create_index(op.f('ix_sys_menu_parent_id'), 'sys_menu', ['parent_id'], unique=False)
    op.create_table(
        'sys_opera_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('trace_id', sa.String(length=32), nullable=False, comment='请求跟踪 ID'),
        sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
        sa.Column('method', sa.String(length=20), nullable=False, comment='请求类型'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='操作模块'),
        sa.Column('path', sa.String(length=500), nullable=False, comment='请求路径'),
        sa.Column('ip', sa.String(length=50), nullable=False, comment='IP地址'),
        sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
        sa.Column('region', sa.String(length=50), nullable=True, comment='地区'),
        sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
        sa.Column('user_agent', sa.String(length=255), nullable=False, comment='请求头'),
        sa.Column('os', sa.String(length=50), nullable=True, comment='操作系统'),
        sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
        sa.Column('device', sa.String(length=50), nullable=True, comment='设备'),
        sa.Column('args', mysql.JSON(), nullable=True, comment='请求参数'),
        sa.Column('status', sa.Integer(), nullable=False, comment='操作状态（0异常 1正常）'),
        sa.Column('code', sa.String(length=20), nullable=False, comment='操作状态码'),
        sa.Column('msg', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='提示消息'),
        sa.Column('cost_time', sa.Float(), nullable=False, comment='请求耗时（ms）'),
        sa.Column('opera_time', sa.DateTime(timezone=True), nullable=False, comment='操作时间'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='操作日志表',
    )
    op.create_index(op.f('ix_sys_opera_log_id'), 'sys_opera_log', ['id'], unique=True)
    op.create_table(
        'sys_role',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='角色名称'),
        sa.Column('status', sa.Integer(), nullable=False, comment='角色状态（0停用 1正常）'),
        sa.Column('is_filter_scopes', sa.Boolean(), nullable=False, comment='过滤数据权限(0否 1是)'),
        sa.Column('remark', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='备注'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='角色表',
    )
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=True)
    op.create_table(
        'sys_role_data_scope',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
        sa.Column('data_scope_id', sa.BigInteger(), nullable=False, comment='数据范围 ID'),
        sa.PrimaryKeyConstraint('id', 'role_id', 'data_scope_id'),
    )
    op.create_index(op.f('ix_sys_role_data_scope_id'), 'sys_role_data_scope', ['id'], unique=True)
    op.create_table(
        'sys_role_menu',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
        sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
        sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
        sa.PrimaryKeyConstraint('id', 'role_id', 'menu_id'),
    )
    op.create_index(op.f('ix_sys_role_menu_id'), 'sys_role_menu', ['id'], unique=True)
    op.create_table(
        'sys_user',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('uuid', sa.String(length=50), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=False, comment='用户名'),
        sa.Column('nickname', sa.String(length=20), nullable=False, comment='昵称'),
        sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
        sa.Column(
            'salt',
            sa.VARBINARY(length=255).with_variant(postgresql.BYTEA(length=255), 'postgresql'),
            nullable=True,
            comment='加密盐',
        ),
        sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
        sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号'),
        sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
        sa.Column('status', sa.Integer(), nullable=False, comment='用户账号状态(0停用 1正常)'),
        sa.Column(
            'is_superuser',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='超级权限(0否 1是)',
        ),
        sa.Column(
            'is_staff',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='后台管理登陆(0否 1是)',
        ),
        sa.Column(
            'is_multi_login',
            sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'),
            nullable=False,
            comment='是否重复登陆(0否 1是)',
        ),
        sa.Column('join_time', sa.DateTime(timezone=True), nullable=False, comment='注册时间'),
        sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True, comment='上次登录时间'),
        sa.Column('last_password_changed_time', sa.DateTime(timezone=True), nullable=True, comment='上次密码变更时间'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uuid'),
        comment='用户表',
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=True)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table(
        'sys_user_role',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
        sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
        sa.PrimaryKeyConstraint('id', 'user_id', 'role_id'),
    )
    op.create_index(op.f('ix_sys_user_role_id'), 'sys_user_role', ['id'], unique=True)
    op.create_table(
        'sys_user_social',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('sid', sa.String(length=255), nullable=False, comment='第三方用户 ID'),
        sa.Column('source', sa.String(length=20), nullable=False, comment='第三方用户来源'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户关联ID'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='用户社交表（OAuth2）',
    )
    op.create_index(op.f('ix_sys_user_social_id'), 'sys_user_social', ['id'], unique=True)
    op.create_table(
        'task_result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task_id', sa.String(length=155), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('result', sa.PickleType(), nullable=True),
        sa.Column('date_done', sa.DateTime(), nullable=True),
        sa.Column('traceback', sa.Text(), nullable=True),
        sa.Column('name', sa.String(length=155), nullable=True),
        sa.Column('args', sa.LargeBinary(), nullable=True),
        sa.Column('kwargs', sa.LargeBinary(), nullable=True),
        sa.Column('worker', sa.String(length=155), nullable=True),
        sa.Column('retries', sa.Integer(), nullable=True),
        sa.Column('queue', sa.String(length=155), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id'),
        comment='任务结果表',
    )
    op.create_table(
        'task_scheduler',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('name', sa.String(length=50), nullable=False, comment='任务名称'),
        sa.Column('task', sa.String(length=255), nullable=False, comment='要运行的 Celery 任务'),
        sa.Column('args', sa.JSON(), nullable=True, comment='任务可接收的位置参数'),
        sa.Column('kwargs', sa.JSON(), nullable=True, comment='任务可接收的关键字参数'),
        sa.Column('queue', sa.String(length=255), nullable=True, comment='CELERY_TASK_QUEUES 中定义的队列'),
        sa.Column('exchange', sa.String(length=255), nullable=True, comment='低级别 AMQP 路由的交换机'),
        sa.Column('routing_key', sa.String(length=255), nullable=True, comment='低级别 AMQP 路由的路由密钥'),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='任务开始触发的时间'),
        sa.Column('expire_time', sa.DateTime(timezone=True), nullable=True, comment='任务不再触发的截止时间'),
        sa.Column('expire_seconds', sa.Integer(), nullable=True, comment='任务不再触发的秒数时间差'),
        sa.Column('type', sa.Integer(), nullable=False, comment='调度类型（0间隔 1定时）'),
        sa.Column('interval_every', sa.Integer(), nullable=True, comment='任务再次运行前的间隔周期数'),
        sa.Column('interval_period', sa.String(length=255), nullable=True, comment='任务运行之间的周期类型'),
        sa.Column('crontab', sa.String(length=50), nullable=True, comment='任务运行的 Crontab 计划'),
        sa.Column(
            'one_off', sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'), nullable=False, comment='是否仅运行一次'
        ),
        sa.Column(
            'enabled', sa.Boolean().with_variant(sa.INTEGER(), 'postgresql'), nullable=False, comment='是否启用任务'
        ),
        sa.Column('total_run_count', sa.Integer(), nullable=False, comment='任务触发的总次数'),
        sa.Column('last_run_time', sa.DateTime(timezone=True), nullable=True, comment='任务最后触发的时间'),
        sa.Column('remark', mysql.LONGTEXT().with_variant(sa.TEXT(), 'postgresql'), nullable=True, comment='备注'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        comment='任务调度表',
    )
    op.create_index(op.f('ix_task_scheduler_id'), 'task_scheduler', ['id'], unique=True)
    op.create_table(
        'task_set_result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('taskset_id', sa.String(length=155), nullable=True),
        sa.Column('result', sa.PickleType(), nullable=True),
        sa.Column('date_done', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('taskset_id'),
        comment='任务集结果表',
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_set_result')
    op.drop_index(op.f('ix_task_scheduler_id'), table_name='task_scheduler')
    op.drop_table('task_scheduler')
    op.drop_table('task_result')
    op.drop_index(op.f('ix_sys_user_social_id'), table_name='sys_user_social')
    op.drop_table('sys_user_social')
    op.drop_index(op.f('ix_sys_user_role_id'), table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_menu_id'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_role_data_scope_id'), table_name='sys_role_data_scope')
    op.drop_table('sys_role_data_scope')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_opera_log_id'), table_name='sys_opera_log')
    op.drop_table('sys_opera_log')
    op.drop_index(op.f('ix_sys_menu_parent_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_login_log_id'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_sys_data_scope_rule_id'), table_name='sys_data_scope_rule')
    op.drop_table('sys_data_scope_rule')
    op.drop_index(op.f('ix_sys_data_scope_id'), table_name='sys_data_scope')
    op.drop_table('sys_data_scope')
    op.drop_index(op.f('ix_sys_data_rule_id'), table_name='sys_data_rule')
    op.drop_table('sys_data_rule')
    op.drop_index(op.f('ix_skill_category_id'), table_name='skill_category')
    op.drop_table('skill_category')
    op.drop_index(op.f('ix_mcp_server_user_id'), table_name='mcp_server')
    op.drop_index(op.f('ix_mcp_server_id'), table_name='mcp_server')
    op.drop_index(op.f('ix_mcp_server_category_id'), table_name='mcp_server')
    op.drop_table('mcp_server')
    op.drop_index(op.f('ix_mcp_category_id'), table_name='mcp_category')
    op.drop_table('mcp_category')
    op.drop_index(op.f('ix_agent_skill_user_id'), table_name='agent_skill')
    op.drop_index(op.f('ix_agent_skill_id'), table_name='agent_skill')
    op.drop_index(op.f('ix_agent_skill_category_id'), table_name='agent_skill')
    op.drop_table('agent_skill')
    op.drop_index(op.f('ix_agent_server_user_id'), table_name='agent_server')
    op.drop_index(op.f('ix_agent_server_id'), table_name='agent_server')
    op.drop_index(op.f('ix_agent_server_category_id'), table_name='agent_server')
    op.drop_table('agent_server')
    op.drop_index(op.f('ix_agent_category_id'), table_name='agent_category')
    op.drop_table('agent_category')
    # ### end Alembic commands ###
