"""add deploy_log table

Revision ID: 96c33d17f4c2
Revises: 1203838f33d1
Create Date: 2026-03-02 23:30:01.097748

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '96c33d17f4c2'
down_revision = '1203838f33d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'deploy_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('task_id', sa.String(length=155), nullable=False, comment='Celery 任务 ID'),
        sa.Column('task_status', sa.String(length=50), nullable=False, comment='任务状态'),
        sa.Column('task_result', sa.Text(), nullable=True, comment='任务结果'),
        sa.Column('traceback', sa.Text(), nullable=True, comment='错误回溯'),
        sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户 ID'),
        sa.Column('server_title', sa.String(length=255), nullable=True, comment='MCP Server 名称'),
        sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
        sa.PrimaryKeyConstraint('id'),
        comment='部署日志表',
    )
    op.create_index(op.f('ix_deploy_log_id'), 'deploy_log', ['id'], unique=True)
    op.create_index(op.f('ix_deploy_log_task_id'), 'deploy_log', ['task_id'], unique=True)
    op.create_index(op.f('ix_deploy_log_user_id'), 'deploy_log', ['user_id'], unique=False)
    op.create_table_comment('agent_chat', '', existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment('agent_chat', existing_comment='', schema=None)
    op.drop_index(op.f('ix_deploy_log_user_id'), table_name='deploy_log')
    op.drop_index(op.f('ix_deploy_log_task_id'), table_name='deploy_log')
    op.drop_index(op.f('ix_deploy_log_id'), table_name='deploy_log')
    op.drop_table('deploy_log')
    # ### end Alembic commands ###
