"""empty message

Revision ID: 1c1ae5d03f1b
Revises: 09ce9664aeab
Create Date: 2026-02-09 14:55:57.062065

"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c1ae5d03f1b'
down_revision = '09ce9664aeab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_server', sa.Column('tools', sa.JSON(), nullable=True, comment='工具列表'))
    op.add_column('agent_server', sa.Column('databases', sa.JSON(), nullable=True, comment='数据库列表'))
    op.add_column('agent_server', sa.Column('skills', sa.JSON(), nullable=True, comment='skills列表'))
    op.drop_column('agent_server', 'tool')
    op.drop_column('agent_server', 'database')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_server', sa.Column('database', mysql.JSON(), nullable=True, comment='数据库列表'))
    op.add_column('agent_server', sa.Column('tool', mysql.JSON(), nullable=True, comment='工具列表'))
    op.drop_column('agent_server', 'skills')
    op.drop_column('agent_server', 'databases')
    op.drop_column('agent_server', 'tools')
    # ### end Alembic commands ###
