"""empty message

Revision ID: 98faadcebbd3
Revises: c504b9716fbc
Create Date: 2026-02-11 15:05:26.607518

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '98faadcebbd3'
down_revision = 'c504b9716fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_server', sa.Column('name', sa.String(length=255), nullable=False, comment='agent name'))
    op.add_column('agent_skill', sa.Column('title', sa.String(length=255), nullable=False, comment='skill title'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_skill', 'title')
    op.drop_column('agent_server', 'name')
    # ### end Alembic commands ###
