export const API_ROUTE_MCPS = "/api/v1/mcp/"
export const API_ROUTE_MY_MCPS = "/api/v1/mcp/mine"
export const API_ROUTE_MCP_CATEGORIES = "/api/v1/mcp/categories"
export const API_ROUTE_MCP_CATEGORIES_RECOMMEND = "/api/v1/mcp/categories/recommend"
export const API_ROUTE_MCP_SERVER_DETAIL = "/api/v1/mcp"
export const API_ROUTE_MCP_SERVER_FEED = "/api/v1/mcp/feed"
export const API_ROUTE_MCP_SERVER_RECOMMEND = "/api/v1/mcp/recommend"
export const API_ROUTE_MCP_ADMIN_SERVERS = "/api/v1/admin/mcp/servers"
export const API_ROUTE_MCP_ADMIN_SERVER_DETAIL = "/api/v1/admin/mcp/servers"
export const API_ROUTE_MCP_ADMIN_CATEGORY = "/api/v1/admin/mcp/categories/get"
export const API_ROUTE_MCP_ADMIN_CATEGORY_CREATE = "/api/v1/admin/mcp/categories/create"
export const API_ROUTE_MCP_DEPLOY_PACKAGE = "/api/v1/mcp/deploy/package"
export const API_ROUTE_OAUTH_USER = "/api/v1/admin/oauth2/user/me"
export const API_ROUTE_AUTH_ME = "/api/v1/admin/auth/me"
export const API_ROUTE_GITHUB_OAUTH2_LOGIN = "/api/v1/admin/oauth/github"
export const API_ROUTE_GOOGLE_OAUTH2_LOGIN = "/api/v1/admin/oauth/google"
export const API_ROUTE_SEND_EMAIL_CODE = "/api/v1/admin/auth/send-code"
export const API_ROUTE_EMAIL_LOGIN = "/api/v1/admin/auth/email-login"

// Agent
export const API_ROUTE_AGENTS = "/api/v1/agent/"
export const API_ROUTE_MY_AGENTS = "/api/v1/agent/mine"
export const API_ROUTE_AGENT_CHAT = "/api/v1/agent/chat"
export const API_ROUTE_AGENT_CATEGORIES = "/api/v1/agent/categories"
export const API_ROUTE_AGENT_ADMIN_SERVERS = "/api/v1/admin/agent/servers"
export const API_ROUTE_AGENT_ADMIN_SERVER_DETAIL = "/api/v1/admin/agent/servers"
export const API_ROUTE_AGENT_ADMIN_CATEGORY = "/api/v1/admin/agent/categories/get"
export const API_ROUTE_AGENT_ADMIN_CATEGORY_CREATE = "/api/v1/admin/agent/categories/create"

// Skill
export const API_ROUTE_SKILLS = "/api/v1/skill/"
export const API_ROUTE_SKILL_CATEGORIES = "/api/v1/skill/categories"
export const API_ROUTE_SKILL_PUBLISH = "/api/v1/skill/publish"
export const API_ROUTE_MY_SKILLS = "/api/v1/skill/mine"
export const API_ROUTE_SKILL_ADMIN_SERVERS = "/api/v1/admin/skill/servers"
export const API_ROUTE_SKILL_ADMIN_SERVER_DETAIL = "/api/v1/admin/skill/servers"
export const API_ROUTE_SKILL_ADMIN_CATEGORY = "/api/v1/admin/skill/categories/get"
export const API_ROUTE_SKILL_ADMIN_CATEGORY_CREATE = "/api/v1/admin/skill/categories/create"

// Sys - User & Role Management
export const API_ROUTE_SYS_USERS = "/api/v1/admin/sys/users"
export const API_ROUTE_SYS_ROLES = "/api/v1/admin/sys/roles"
export const API_ROUTE_SYS_MENUS = "/api/v1/admin/sys/menus"
