export const API_ROUTE_MCP_SEARCH = "/api/v1/mcp/search"
export const API_ROUTE_MCP_CATEGORIES = "/api/v1/mcp/categories"
export const API_ROUTE_MCP_REGISTRY_SEARCH = "/api/v1/mcp/server/registry/search"
export const API_ROUTE_MCP_SERVER_DETAIL = "/api/v1/mcp"
export const API_ROUTE_MCP_SERVER_CALL = "/api/v1/mcp/invoke"
export const API_ROUTE_MCP_SERVER_FEED = "/api/v1/mcp/server/registry/feed"
export const API_ROUTE_MCP_SERVER_RECOMMEND = "/api/v1/mcp/recommend"
export const API_ROUTE_MCP_ADMIN_SERVERS = "/api/v1/admin/mcp/servers"
export const API_ROUTE_MCP_ADMIN_SERVER_DETAIL = "/api/v1/admin/mcp/servers"
export const API_ROUTE_MCP_ADMIN_CATEGORY = "/api/v1/admin/mcp/categories/get"
export const API_ROUTE_MCP_ADMIN_CATEGORY_CREATE = "/api/v1/admin/mcp/categories/create"
export const API_ROUTE_MCP_COMPILE_STDIO = "/api/v1/mcp/compile/stdio"
export const API_ROUTE_MCP_DEPLOY_PACKAGE = "/api/v1/mcp/deploy/package"
export const API_ROUTE_OAUTH_USER = "/api/v1/admin/oauth2/user/me"
export const API_ROUTE_AUTH_ME = "/api/v1/admin/auth/me"
export const API_ROUTE_GITHUB_OAUTH2_LOGIN = "/api/v1/admin/oauth/github"
export const API_ROUTE_GOOGLE_OAUTH2_LOGIN = "/api/v1/admin/oauth/google"

// Agent
export const API_ROUTE_AGENT_SEARCH = "/api/v1/agent/search"
export const API_ROUTE_AGENT_CATEGORIES = "/api/v1/agent/categories"
export const API_ROUTE_AGENT_ADMIN_SERVERS = "/api/v1/admin/agent/servers"
export const API_ROUTE_AGENT_ADMIN_SERVER_DETAIL = "/api/v1/admin/agent/servers"

// Skill
export const API_ROUTE_SKILL_SEARCH = "/api/v1/skill/search"
export const API_ROUTE_SKILL_CATEGORIES = "/api/v1/skill/categories"
export const API_ROUTE_SKILL_PUBLISH = "/api/v1/skill/publish"
